[build]
  publish = "."

[[redirects]]
  from = "/especialidades"
  to = "/especialidades/musicos-artistas.html"
  status = 301

[[redirects]]
  from = "/especialidades/"
  to = "/especialidades/musicos-artistas.html"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
